/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author orian
 */
public class food extends javax.swing.JFrame {

    /**
     * Creates new form food
     */
    public food() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        waterButton = new javax.swing.JButton();
        candiesButton = new javax.swing.JButton();
        ramenButton = new javax.swing.JButton();
        cerealButton = new javax.swing.JButton();
        returnButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("Food");

        waterButton.setBackground(new java.awt.Color(255, 204, 0));
        waterButton.setText("Water");
        waterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waterButtonActionPerformed(evt);
            }
        });

        candiesButton.setBackground(new java.awt.Color(255, 204, 0));
        candiesButton.setText("Candies");
        candiesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                candiesButtonActionPerformed(evt);
            }
        });

        ramenButton.setBackground(new java.awt.Color(255, 204, 0));
        ramenButton.setText("Ramen");
        ramenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ramenButtonActionPerformed(evt);
            }
        });

        cerealButton.setBackground(new java.awt.Color(255, 204, 0));
        cerealButton.setText("Cereal");
        cerealButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerealButtonActionPerformed(evt);
            }
        });

        returnButton6.setBackground(new java.awt.Color(255, 204, 0));
        returnButton6.setText("Return");
        returnButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(returnButton6)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(waterButton)
                    .addComponent(ramenButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 422, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(candiesButton)
                    .addComponent(cerealButton))
                .addGap(133, 133, 133))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(returnButton6))
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(waterButton)
                    .addComponent(candiesButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ramenButton)
                        .addGap(188, 188, 188))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cerealButton)
                        .addGap(180, 180, 180))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void waterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waterButtonActionPerformed
        // TODO add your handling code here:
            new water().setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_waterButtonActionPerformed

    private void candiesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_candiesButtonActionPerformed
        // TODO add your handling code here:
            new candies().setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_candiesButtonActionPerformed

    private void ramenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ramenButtonActionPerformed
        // TODO add your handling code here:
            new ramen().setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_ramenButtonActionPerformed

    private void cerealButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerealButtonActionPerformed
        // TODO add your handling code here:
            new cereal().setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_cerealButtonActionPerformed

    private void returnButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButton6ActionPerformed
        // TODO add your handling code here:
               new CobberStoreMain().setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_returnButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new food().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton candiesButton;
    private javax.swing.JButton cerealButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton ramenButton;
    private javax.swing.JButton returnButton6;
    private javax.swing.JButton waterButton;
    // End of variables declaration//GEN-END:variables
}
