/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author orian
 */
public class electronics extends javax.swing.JFrame {

    /**
     * Creates new form electronics
     */
    public electronics() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        chargerButton = new javax.swing.JButton();
        laptopButton = new javax.swing.JButton();
        tabletButton = new javax.swing.JButton();
        headphonesButton = new javax.swing.JButton();
        returnButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("Electronics");

        chargerButton.setBackground(new java.awt.Color(255, 204, 0));
        chargerButton.setText("Charger");
        chargerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chargerButtonActionPerformed(evt);
            }
        });

        laptopButton.setBackground(new java.awt.Color(255, 204, 0));
        laptopButton.setText("Laptop");
        laptopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laptopButtonActionPerformed(evt);
            }
        });

        tabletButton.setBackground(new java.awt.Color(255, 204, 0));
        tabletButton.setText("Tablet");
        tabletButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabletButtonActionPerformed(evt);
            }
        });

        headphonesButton.setBackground(new java.awt.Color(255, 204, 0));
        headphonesButton.setText("Headphones");
        headphonesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                headphonesButtonActionPerformed(evt);
            }
        });

        returnButton8.setBackground(new java.awt.Color(255, 204, 0));
        returnButton8.setText("Return");
        returnButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 471, Short.MAX_VALUE)
                .addComponent(returnButton8)
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chargerButton)
                    .addComponent(tabletButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(headphonesButton)
                        .addGap(98, 98, 98))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(laptopButton)
                        .addGap(142, 142, 142))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(returnButton8)))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chargerButton)
                    .addComponent(laptopButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 232, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tabletButton)
                    .addComponent(headphonesButton))
                .addGap(176, 176, 176))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chargerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chargerButtonActionPerformed
        // TODO add your handling code here:
    new charger().setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_chargerButtonActionPerformed

    private void laptopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laptopButtonActionPerformed
        // TODO add your handling code here:
            new laptop().setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_laptopButtonActionPerformed

    private void tabletButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabletButtonActionPerformed
        // TODO add your handling code here:
           new tablet().setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_tabletButtonActionPerformed

    private void headphonesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_headphonesButtonActionPerformed
        // TODO add your handling code here:
    new heaphones().setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_headphonesButtonActionPerformed

    private void returnButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButton8ActionPerformed
        // TODO add your handling code here:
               new CobberStoreMain().setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_returnButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(electronics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(electronics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(electronics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(electronics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new electronics().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chargerButton;
    private javax.swing.JButton headphonesButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton laptopButton;
    private javax.swing.JButton returnButton8;
    private javax.swing.JButton tabletButton;
    // End of variables declaration//GEN-END:variables
}
